config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  
  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get "static_pages/home"

  resources :articles
  resources :subtopics
  resources :topics
  resources :subjects

end

app/views/layouts/_footer.html.erb
<div class="bottom-menu bottom-menu-large bottom-menu-inverse">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-3">
            <a href="/" class="bottom-menu-brand">SwimRocket</a>
          </div>
          <% @topics.each do |topic|%>
            <div class="col-md-3 col-sm-3">
              <a href="/topics/<%=topic.id%>"><h5 class="title"><%=topic.name.upcase%></h5></a>
              <% topic.subtopics.each do |subtopic| %>
                <ul class="bottom-menu-list">
                  <li><a href="/subtopics/<%=subtopic.id%>"><%=subtopic.name%></a></li>
                </ul>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/layouts/_header-backup.html.erb
<script>
  $(".tab-<%= @section %>").addClass("active")
</script>         
<header class="header-20">
  <div class="container">
      <div class="row">
          <nav class="navbar col-sm-12" role="navigation">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle"></button>
                  <a class="brand" href="/"><img src="/assets/flat-ui-pro/icons/rocket.svg" width="50" height="50" alt=""> SwimRocket</a>
              </div>
              <div class="collapse navbar-collapse pull-right">
                  <ul class="nav pull-left">
                    <% @topics.each do |topic| %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= topic.name %><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <% topic.subtopics.each do |subtopic| %>
                            <li><a href=<%="/subtopics/#{subtopic.id}"%>><%= subtopic.name %></a></li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                    <li><a href="<%=signin_path%>">Sign In</a></li>
                    <% if signed_in? %>
                      <li class="dropdown">
                        <a href = "/user/<%=@current_user.id%>"class="dropdown-toggle" data-toggle = "dropdown" role = "button" aria-expanded="false">

                          <%=@current_user.name%>
                          </span>
                          <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu" role="menu">
                              <li>
                                <a href=<%="/users/#{@current_user.id}"%>>
                                <i class="icon-user"></i> Profile </a>
                              </li>
                              <li>
                                <a href=<%="#{edit_user_path(current_user)}"%>>
                                <i class="icon-lock"></i> Settings </a>
                              </li>
                              <li class="divider">
                              </li>
                              <li>
                                <a data-method="delete" href="/signout" rel="nofollow">
                                <i class="icon-key"></i> Sign Out </a>
                              </li>
                            </ul>
                  <% else %>

                  </ul>
                      <ul class="nav navbar-nav">
                        
                      </ul> 
                    <% end %>
                  </ul>
                  <form class="navbar-form pull-left">  

                  </form>
              </div>
          </nav>
      </div>
  </div>
  <div class="header-background"></div>
</header>

app/views/layouts/_header.html.erb
<script>
  $(".tab-<%= @section %>").addClass("active")
</script>         
<header class="header-20">
  <div class="container">
      <div class="row">
          <nav class="navbar col-sm-12" role="navigation">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle"></button>
                  <a class="brand" href="/"><img src="/assets/flat-ui-pro/icons/rocket.svg" width="50" height="50" alt=""> SwimRocket</a>
              </div>
              <div class="collapse navbar-collapse pull-right">
                  <ul class="nav pull-left">
                    <% @topics.each do |topic| %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= topic.name %><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <% topic.subtopics.each do |subtopic| %>
                            <li><a href=<%="/subtopics/#{subtopic.id}"%>><%= subtopic.name %></a></li>
                          <% end %>
                        </ul>
                      </li>
                    <% end %>
                    <li><a href="<%=signin_path%>">Sign In</a></li>
                    <% if signed_in? %>
                      <li class="dropdown">
                        <a href = "/user/<%=@current_user.id%>"class="dropdown-toggle" data-toggle = "dropdown" role = "button" aria-expanded="false">

                          <%=@current_user.name%>
                          </span>
                          <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu" role="menu">
                              <li>
                                <a href=<%="/users/#{@current_user.id}"%>>
                                <i class="icon-user"></i> Profile </a>
                              </li>
                              <li>
                                <a href=<%="#{edit_user_path(current_user)}"%>>
                                <i class="icon-lock"></i> Settings </a>
                              </li>
                              <li class="divider">
                              </li>
                              <li>
                                <a data-method="delete" href="/signout" rel="nofollow">
                                <i class="icon-key"></i> Sign Out </a>
                              </li>
                            </ul>
                  <% else %>

                  </ul>
                      <ul class="nav navbar-nav">
                        
                      </ul> 
                    <% end %>
                  </ul>
                  <form class="navbar-form pull-left">  

                  </form>
              </div>
          </nav>
      </div>
  </div>
  <div class="header-background"></div>
</header>

app/views/layouts/_header.html.haml
:javascript
  $(".tab-#{@section}").addClass("active")
%header.header-20
  .container
    .row
      %nav.navbar.col-sm-12{:role => "navigation"}
        .navbar-header
          %button.navbar-toggle{:type => "button"}
          %a.brand{:href => "/"}
            %img{:alt => "", :height => "50", :src => image_path("flat-ui-pro/icons/rocket.svg"), :width => "50"}/
            SwimRocket
        .collapse.navbar-collapse.pull-right
          %ul.nav.pull-left
            - @topics.each do |topic|
              %li.dropdown
                %a.dropdown-toggle{:href => topic_path(topic)}
                  = topic.name
                        
                / %a.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                /   = topic.name
                /   %span.caret
                / %ul.dropdown-menu{:role => "menu"}
                /   - topic.subtopics.each do |subtopic|
                /     %li
                /       %a{:href => "/subtopics/#{subtopic.id}"}
                /         #{subtopic.name}

            - if signed_in?
              %li
                %a{:href => "/users/#{@current_user.id}", :role => "button"}
                  = @current_user.name
                /   %i.fa.fa-angle-down
                / %ul.dropdown-menu{:role => "menu"}
                /   %li
                /     %a{:href => "/users/#{@current_user.id}"}
                /       %i.icon-user
                /       Profile

            - else
              %li
                %a{:href => signin_path} Sign In
          %ul.nav.navbar-nav
          %form.navbar-form.pull-left
  .header-background

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application-backup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="">
    <%= render 'layouts/header' %>
    <div style = "padding-top: 20px, padding-bottom: 20px">
      <div class = "container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="" style = "background-color: #ecf0f1">
    <%= render 'layouts/header' %>
    <div class="">
      <div class = "">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %meta{:content => "black", :name => "apple-mobile-web-app-status-bar-style"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
    %link{:href => "/favicon.ico", :rel => "icon", :type => "image/x-icon"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
    %meta{:content => "qatxs95erj3Li1E2To-J2sCbKXzM3-3tRPToy-guR0w", :name => "google-site-verification"}/
  %body
    .page-wrapper
      
      = render 'layouts/header'
      %div.main-container
        .container
          - flash.each do |key, value|
            = content_tag(:div, value, class: "alert alert-#{key}")
          - if @section != 'home'
            = yield
        - if @section == 'home'
          = yield
      = render 'layouts/footer' 
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58664426-1', 'auto');
  ga('send', 'pageview');